CREATE TABLE "productos" (
  "producto_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" varchar(255),
  "activo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "categoria_id" integer NOT NULL
);

CREATE TABLE "categorias" (
  "categoria_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "parent_id" integer
);

CREATE TABLE "tela" (
  "tela_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30) NOT NULL
);

INSERT INTO tela (nombre) VALUES 
('Liso'), 
('Estampado'), 
('Rayado'), 
('Cuadrillé');

CREATE TABLE "sizes" (
  "size_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" varchar(20) NOT NULL,
  "type_id" integer NOT NULL
);

INSERT INTO size_types (nombre) VALUES 
('Medidas Almohadones'), 
('General');

CREATE TABLE "size_types" (
  "type_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL
);

-- Medidas para Almohadones (type_id = 1)
INSERT INTO sizes (valor, type_id) VALUES 
('40x40', 1), 
('45x45', 1), 
('50x50', 1), 
('40x60', 1), 
('50x60', 1);

-- Talle Único para el resto (type_id = 2)
INSERT INTO sizes (valor, type_id) VALUES 
('Talle Único', 2);

CREATE TABLE "variantes_producto" (
  "variante_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" integer NOT NULL,
  "tela_id" integer NOT NULL,
  "size_id" integer NOT NULL,
  "stock" integer NOT NULL DEFAULT 0,
  -- Los precios ahora viven aquí:
  "precio" numeric(10,2) NOT NULL,
  "precio_oferta" numeric(10,2),
  "en_oferta" boolean DEFAULT false,
  "activo" boolean DEFAULT true -- Agregué esto por si querés dar de baja una variante sin borrarla
);

-- 1. Creamos la tabla con la estructura que pasaste
CREATE TABLE "imagenes_variantes" (
  "img_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" TEXT NOT NULL,
  "principal" BOOLEAN DEFAULT false,
  "variante_id" INTEGER NOT NULL
);

-- 2. Agregamos la relación con la tabla de variantes
-- Asegurate que tu tabla de variantes se llame "variantes_producto"
ALTER TABLE "imagenes_variantes"
ADD CONSTRAINT fk_variante
FOREIGN KEY ("variante_id")
REFERENCES "variantes_producto" ("variante_id")
ON DELETE CASCADE;

-- 3. (Opcional pero RECOMENDADO)
-- Creamos un índice para que las búsquedas de fotos por variante sean rápidas
CREATE INDEX idx_variante_id ON "imagenes_variantes"("variante_id");

CREATE TABLE "clientes" (
  "cliente_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(100) UNIQUE NOT NULL,
  "activo" boolean DEFAULT TRUE,
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE "ventas" (
  "venta_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "total" numeric(12,2) NOT NULL,
  "metodo_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "cliente_id" integer NOT NULL,
  "estado_id" integer NOT NULL
);

CREATE TABLE "metodos_pago" (
  "metodo_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50) NOT NULL
);
INSERT INTO metodos_pago (descripcion) VALUES ('Efectivo'), ('Transferencia Bancaria');

CREATE TABLE "estados_venta" (
  "estado_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50) NOT NULL
);

INSERT INTO estados_venta (descripcion) VALUES ('pendiente'), ('confirmada'), ('cancelada'), ('anulada');

CREATE TABLE "detalle_ventas" (
  "detalle_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" integer NOT NULL,
  "precio_unitario" numeric(12,2) NOT NULL,
  "venta_id" integer NOT NULL,
  "variante_id" integer NOT NULL
);

CREATE TABLE "productos_home" (
  "home_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden" integer DEFAULT 0,
  "activo" boolean DEFAULT true,
  "producto_id" integer NOT NULL
);

CREATE TABLE "carousel_home" (
  "carousel_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "img_desktop_url" text,
  "img_mobile_url" text,
  "orden" integer DEFAULT 0,
  "activo" boolean DEFAULT true,
  "producto_id" integer,
  "categoria_id" integer
);

CREATE TABLE "usuarios" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "contrasenia" varchar(255) NOT NULL,
  "rol_id" integer NOT NULL
);

INSERT INTO "usuarios" (nombre, email, contrasenia, rol_id) 
VALUES (
  'Dueño Decoeclat', 
  'admin@decoeclat.com.ar', 
  '$2b$10$9ZIQ0LSO6/66o49/DX3NFOIUTI0kDN3OfJikeN7VH4HM.O963TjqS', -- Hash para 'admin123'
  1 -- Rol de Administrador
);

CREATE TABLE "roles" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50) NOT NULL
);

INSERT INTO "roles" (descripcion) 
VALUES 
  ('Administrador'), -- Será ID 1
  ('Vendedor'),      -- Será ID 2
  ('Depósito');      -- Será ID 3

ALTER TABLE "productos" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("categoria_id");

ALTER TABLE "categorias" ADD FOREIGN KEY ("parent_id") REFERENCES "categorias" ("categoria_id");

ALTER TABLE "sizes" ADD FOREIGN KEY ("type_id") REFERENCES "size_types" ("type_id");

ALTER TABLE "variantes_producto" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "variantes_producto" ADD FOREIGN KEY ("tela_id") REFERENCES "tela" ("tela_id");

ALTER TABLE "variantes_producto" ADD FOREIGN KEY ("size_id") REFERENCES "sizes" ("size_id");

ALTER TABLE "ventas" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("cliente_id");

ALTER TABLE "ventas" ADD FOREIGN KEY ("metodo_id") REFERENCES "metodos_pago" ("metodo_id");

ALTER TABLE "ventas" ADD FOREIGN KEY ("estado_id") REFERENCES "estados_venta" ("estado_id");

ALTER TABLE "detalle_ventas" ADD FOREIGN KEY ("venta_id") REFERENCES "ventas" ("venta_id");

ALTER TABLE "detalle_ventas" ADD FOREIGN KEY ("variante_id") REFERENCES "variantes_producto" ("variante_id");

ALTER TABLE "productos_home" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "carousel_home" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "carousel_home" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("categoria_id");

ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("rol_id");

-- Categorías padre
INSERT INTO categorias (nombre, parent_id) VALUES
('Textiles', NULL),
('Cestería', NULL),
('Para la Mesa', NULL),
('Para la Cocina', NULL),
('Kids', NULL);

-- Subcategorías
INSERT INTO categorias (nombre, parent_id)
VALUES
('Lonitas', (SELECT categoria_id FROM categorias WHERE nombre = 'Textiles')),
('Fundas', (SELECT categoria_id FROM categorias WHERE nombre = 'Textiles')),
('Mantas', (SELECT categoria_id FROM categorias WHERE nombre = 'Textiles')),
('Almohadones', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids')),
('Cestos', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids')),
('Contenedores', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids')),
('Alfombras', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids'));
